import "./profile-cpu.test.js";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { parse } from "yaml";
const workflow = parse(await fs.readFile(new URL("../../.github/workflows/map-diagnostic.yml", import.meta.url), "utf8"));
assert.deepEqual(Object.keys(workflow.on).sort(), ["push", "workflow_dispatch"]);
assert.deepEqual(workflow.on.push.branches, ["codex/diagnose-map/**"]);
assert.deepEqual(workflow.permissions, { contents: "read" });
assert.deepEqual(Object.keys(workflow.jobs), ["map-diagnostic"]);
const job = workflow.jobs["map-diagnostic"];
assert.equal(job["timeout-minutes"], 10);
assert.equal(job.env.GEORISK_DIAGNOSTIC_PROFILE, "${{ inputs.profile || 'mobile' }}");
const scan = job.steps.findIndex(step => step.id === "security-scan");
const diagnostic = job.steps.findIndex(step => step.run === "node scripts/runMapDiagnostic.js");
const upload = job.steps.findIndex(step => step.uses?.startsWith("actions/upload-artifact@"));
assert.ok(scan >= 0 && diagnostic > scan && upload > diagnostic);
assert.equal(job.steps[scan].run, "node scripts/checkSecurity.js --history");
assert.equal(job.steps[upload].if, "always() && steps.security-scan.outcome == 'success'");
assert.equal(job.steps[upload].with["retention-days"], 7);
assert.equal(job.steps[upload].with.path.trim(), "reports/startup-profile.json\nreports/map-diagnostic-cpu.json");
assert.ok(job.steps.every(step => !/pages|deploy/.test(step.uses || "")));
console.log("map-diagnostic.test.js ok: explicit trigger, read-only permissions, scan-gated bounded diagnostic artifacts");
