import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";

const sources = [
  ["html2canvas", "1.4.1", "dist/html2canvas.min.js", "html2canvas-1.4.1.min.js"],
  ["jspdf", "4.2.1", "dist/jspdf.umd.min.js", "jspdf-4.2.1.umd.min.js"]
];
const digest = (value, algorithm, encoding) => createHash(algorithm).update(value).digest(encoding);

export async function buildExportLibraries({ root = process.cwd(), check = false } = {}) {
  const project = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8"));
  const lock = JSON.parse(await fs.readFile(path.join(root, "package-lock.json"), "utf8"));
  const assets = {};
  const files = [];
  const licenses = [];
  for (const [name, version, source, filename] of sources) {
    const packageRoot = path.join(root, "node_modules", name);
    const metadata = JSON.parse(await fs.readFile(path.join(packageRoot, "package.json"), "utf8"));
    if (metadata.version !== version || project.devDependencies[name] !== version ||
        lock.packages[`node_modules/${name}`]?.version !== version) {
      throw new Error(`Export dependency mismatch: ${name}@${version}. Run npm ci.`);
    }
    // Keep upstream bytes and embedded notices unchanged; source maps are not published.
    const contents = await fs.readFile(path.join(packageRoot, source));
    const file = `vendor/exports/${filename}`;
    assets[name] = {
      version, path: file, bytes: contents.length,
      sha256: digest(contents, "sha256", "hex"),
      integrity: `sha384-${digest(contents, "sha384", "base64")}`
    };
    files.push([file, contents]);
    licenses.push(`===== ${name}@${version} =====\n\n${(await fs.readFile(path.join(packageRoot, "LICENSE"), "utf8")).replace(/\r\n/g, "\n").trim()}`);
  }
  files.push(["vendor/exports/LICENSES.txt", Buffer.from(licenses.join("\n\n") + "\n")]);
  files.push(["vendor/exports/manifest.js", Buffer.from(
    "// Generated by npm run build:export-libs. Do not edit.\n" +
    `export const exportAssets = ${JSON.stringify(assets, null, 2)};\n`
  )]);
  for (const [file, contents] of files) {
    const absolute = path.join(root, file);
    const existing = await fs.readFile(absolute).catch(() => null);
    if (existing?.equals(contents)) continue;
    if (check) throw new Error(`${file} is stale or modified. Run npm run build:export-libs.`);
    await fs.mkdir(path.dirname(absolute), { recursive: true });
    await fs.writeFile(absolute, contents);
  }
  return assets;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const assets = await buildExportLibraries({ check: process.argv.includes("--check") });
  console.log(`Export libraries verified: ${Object.values(assets).map(asset => `${asset.path} (${asset.bytes} bytes)`).join(", ")}`);
}
